version: "3"
services:
    db01:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: my_db
            MYSQL_USER: root
            MYSQL_PASSWORD: pass
        ports:
            - "9906:3306"
        networks:
            - default
    www01:
        build: .
        ports:
            - "1025:80"
        volumes:
            - ./src:/var/www/html/
        networks:
            - default
        depends_on:
            - db01